# Descrição:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#						1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib_menos_um = 0
fib_menos_dois = 1
resultado_fib = 0
soma_fib_par = 0
while(resultado_fib<=4000000):
    resultado_fib = fib_menos_um + fib_menos_dois
    if(resultado_fib%2==0):
        soma_fib_par+=resultado_fib
    fib_menos_dois = fib_menos_um
    fib_menos_um = resultado_fib
print(soma_fib_par)